In [1]:
 import requests

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [2]:
import pandas as pd

df = pd.DataFrame(documents, columns=['course', 'section', 'question', 'text'])
df.tail()

course                   section  \
943  mlops-zoomcamp  Module 6: Best practices   
944  mlops-zoomcamp  Module 6: Best practices   
945  mlops-zoomcamp  Module 6: Best practices   
946  mlops-zoomcamp  Module 6: Best practices   
947  mlops-zoomcamp  Module 6: Best practices   

                                              question  \
943  Github actions: Permission denied error when e...   
944  Managing Multiple Docker Containers with docke...   
945           AWS regions need to match docker-compose   
946                                   Isort Pre-commit   
947  How to destroy infrastructure created via GitH...   

                                                  text  
943  Problem description\nThis is the step in the c...  
944  Problem description\nWhen a docker-compose fil...  
945  Problem description\nIf you are having problem...  
946  Problem description\nPre-commit command was fa...  
947  Problem description\nInfrastructure created in...

In [3]:
df[df.course == 'data-engineering-zoomcamp']

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
1    data-engineering-zoomcamp  General course-related questions   
2    data-engineering-zoomcamp  General course-related questions   
3    data-engineering-zoomcamp  General course-related questions   
4    data-engineering-zoomcamp  General course-related questions   
..                         ...                               ...   
430  data-engineering-zoomcamp           Workshop 2 - RisingWave   
431  data-engineering-zoomcamp           Workshop 2 - RisingWave   
432  data-engineering-zoomcamp           Workshop 2 - RisingWave   
433  data-engineering-zoomcamp          Triggers in Mage via CLI   
434  data-engineering-zoomcamp          Triggers in Mage via CLI   

                                              question  \
0                 Course - When will the course start?   
1    Course - What are the prerequisites for this c...   
2    Course - Can I still join the course after the...   
3    Course - I have registered for the Data Engine...   
4     Course - What can I do before the course starts?   
..                                                 ...   
430  Unable to Open Dashboard as xdg-open doesn’t o...   
431  Resolving Python Interpreter Path Inconsistenc...   
432                    How does windowing work in Sql?   
433  Encountering the error "ModuleNotFoundError: N...   
434                                     Basic Commands   

                                                  text  
0    The purpose of this document is to capture fre...  
1    GitHub - DataTalksClub data-engineering-zoomca...  
2    Yes, even if you don't register, you're still ...  
3    You don't need it. You're accepted. You can al...  
4    You can start by installing and setting up all...  
..                                                 ...  
430  Refer to the solution given in the first solut...  
431  Example Error:\nWhen attempting to execute a P...  
432  Ans : Windowing in streaming SQL involves defi...  
433  Python 3.12.1, is not compatible with kafka-py...  
434  Docker Commands\n# Create a Docker Image from ...  

[435 rows x 4 columns]

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(stop_words='english')
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names)
df_docs

00  00000000e  0002  00021  001  009s   01   02  020  028879  ...  \
0    0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   
1    0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   
2    0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   
3    0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   
4    0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   
..   ...        ...   ...    ...  ...   ...  ...  ...  ...     ...  ...   
943  0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   
944  0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   
945  0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   
946  0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   
947  0.0        0.0   0.0    0.0  0.0   0.0  0.0  0.0  0.0     0.0  ...   

     zoompcamp  zshrc  ángel  çelik  开启屏幕阅读器支持   斜杠  查找和替换  要了解键盘快捷键  \
0          0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   
1          0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   
2          0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   
3          0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   
4          0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   
..         ...    ...    ...    ...        ...  ...    ...       ...   
943        0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   
944        0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   
945        0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   
946        0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   
947        0.0    0.0    0.0    0.0        0.0  0.0    0.0       0.0   

     要启用屏幕阅读器支持  请按ctrl  
0           0.0     0.0  
1           0.0     0.0  
2           0.0     0.0  
3           0.0     0.0  
4           0.0     0.0  
..          ...     ...  
943         0.0     0.0  
944         0.0     0.0  
945         0.0     0.0  
946         0.0     0.0  
947         0.0     0.0  

[948 rows x 6461 columns]

In [41]:
query = "I just discovered the course. Is it too late to join?"

q = cv.transform([query])
q.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

score = cosine_similarity(X, q).flatten()

In [43]:
import numpy as np
np.argsort(score)[-5:]

array([440,  15,  22, 449,   0])

In [48]:
df.iloc[449].text

'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.'

In [11]:
query_dict = dict(zip(names, q.toarray()[0]))
query_dict

0.38148200594064524

In [60]:
matrices = {}
vectorizers = {}

fields = ['section', 'question', 'text']

for field in fields:
  cv = TfidfVectorizer(stop_words='english', min_df=5)
  X = cv.fit_transform(df[field])

  matrices[field] = X
  vectorizers[field] = cv


In [78]:
n = len(df)

score = np.zeros(n)

boosts = {
  'question': 3
}
from sklearn.metrics.pairwise import cosine_similarity

query = "I just signed up. Is it too late to join the course?"

for field in fields:
  q = vectorizers[field].transform([query])
  X = matrices[field]

  f_score = cosine_similarity(X, q).flatten()

  boost = boosts.get(field, 1.0)
  score = score + boost * f_score

idx = np.argsort(-score)[:5]

In [79]:
filters = {
  'course': 'data-engineering-zoomcamp'
}

for field, value in filters.items():
  mask = (df[field] == value).astype(int).values
  score = score * mask

score

array([3.52985023, 3.49512426, 2.70735166, 2.96614194, 3.49512426,
       3.49512426, 1.93689291, 3.67069698, 2.67242848, 3.49512426,
       3.10198469, 2.46096752, 0.49512426, 0.49512426, 0.49512426,
       0.59193348, 0.49512426, 2.63772182, 0.57041627, 0.49512426,
       0.49512426, 0.49512426, 0.79499188, 0.60033101, 0.49512426,
       0.49512426, 0.49512426, 0.76959902, 0.62340833, 0.49512426,
       0.49512426, 0.49512426, 0.49512426, 1.78972334, 3.49512426,
       1.72080809, 0.49512426, 0.49512426, 0.49512426, 0.52668735,
       0.54427244, 2.00115141, 0.49512426, 0.53842198, 0.        ,
       0.        , 0.        , 0.        , 0.02804374, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06739038, 0.        , 0.00980845,
       0.        , 0.        , 0.        , 0.        , 0.05820102,
       0.        , 0.        , 0.        , 0.        , 0.     

In [80]:
idx = np.argsort(-score)[:5]
df.iloc[idx]

course                           section  \
7  data-engineering-zoomcamp  General course-related questions   
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   
5  data-engineering-zoomcamp  General course-related questions   

                                            question  \
7  Course - Can I follow the course after it fini...   
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
4   Course - What can I do before the course starts?   
5             Course - how many Zoomcamps in a year?   

                                                text  
7  Yes, we will keep all the materials after the ...  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
4  You can start by installing and setting up all...  
5  There are 3 Zoom Camps in a year, as of 2024. ...

In [ ]:
class TextSearch:

    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params={}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            cv = TfidfVectorizer(**vectorizer_params)
            X = cv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = cv

    def search(self, query, n_results=10, boost={}, filters={}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s

        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient='records')

In [ ]:
index = TextSearch(
    text_fields=['section', 'question', 'text']
)
index.fit(documents)

index.search(
    query='I just singned up. Is it too late to join the course?',
    n_results=5,
    boost={'question': 3.0},
    filters={'course': 'data-engineering-zoomcamp'}
)